

export const allProducts = [
  //coffee
  {
    product: 'coffee',                       //продукт
    cookingMethod: 'Турка',                  //способ приготовления 1
    methodProcessing: 'Сухая',               //способ обработки 5
    degreeFrying: 4,                         //степень обжарки 2
    geography: 'Африка',                     //география 3
    typeCoffee: 'Робуста',                   //вид кофе 7
    sale: false,                             //скидки
    special: ['Популярное', 'Новый урожай'], //особые 6
    rating: 4,                               //рейтинг
    acid: 'Низкая',                          //кислинка 4
    image: '../images/Discount Goods/01.png',//картинка
    title: 'Colombia Supremo',               //заголовок
    description: ['Свежеобжаренный кофе',    //описание
      '- описание товара, вкус, аромат'],
    price: '250',                            //цена
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Мытая',
    degreeFrying: 5,
    geography: 'Йемен',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Ваш выбор'],
    rating: 5,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Мока',
    methodProcessing: 'Прочие',
    degreeFrying: 3,
    geography: 'Уганда',
    typeCoffee: 'Смесь арабика/робуста',
    sale: true,
    special: ['Скидки'],
    rating: 3,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Эспрессо',
    methodProcessing: 'Сухая',
    degreeFrying: 5,
    geography: 'Эфиопия',
    typeCoffee: 'Арабика',
    sale: false,
    special: ['Сорт недели'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Воронка',
    methodProcessing: 'Мытая',
    degreeFrying: 5,
    geography: 'Азия',
    typeCoffee: 'Робуста',
    sale: false,
    special: ['Микролот'],
    rating: 4,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Аэропресс',
    methodProcessing: 'Прочие',
    degreeFrying: 5,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Новинка'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Чашка',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Лат. Америка',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Популярное', 'Новый урожай'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Автомат',
    methodProcessing: 'Мытая',
    degreeFrying: 4,
    geography: 'Африка',
    typeCoffee: 'Робуста',
    sale: false,
    special: ['Ваш выбор'],
    rating: 4,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Йемен',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Сорт недели'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Уганда',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Микролот'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Мока',
    methodProcessing: 'Мытая',
    degreeFrying: 4,
    geography: 'Эфиопия',
    typeCoffee: 'Арабика',
    sale: false,
    special: ['Новинка'],
    rating: 4,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Эспрессо',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Азия',
    typeCoffee: 'Робуста',
    sale: false,
    special: ['Популярное', 'Новый урожай'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  //===================== 12 штук
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Мытая',
    degreeFrying: 4,
    geography: 'Уганда',
    typeCoffee: 'Арабика',
    sale: false,
    special: ['Ваш выбор'],
    rating: 4,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Эфиопия',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Микролот'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Азия',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Скидки'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Новинка'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Турка',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Лат. Америка',
    typeCoffee: 'Смесь арабик',
    sale: false,
    special: ['Сорт недели'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Прочие',
    degreeFrying: 4,
    geography: 'Африка',
    typeCoffee: 'Арабика',
    sale: false,
    special: ['Популярное', 'Новый урожай'],
    rating: 4,
    acid: 'Высокая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Лат. Америка',
    typeCoffee: 'Робуста',
    sale: false,
    special: ['Сорт недели'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабика/робуста',
    sale: true,
    special: ['Скидки'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабика/робуста',
    sale: true,
    special: ['Скидки'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабика/робуста',
    sale: true,
    special: ['Скидки'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Эфиопия',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Микролот'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Френч-пресс',
    methodProcessing: 'Сухая',
    degreeFrying: 4,
    geography: 'Азия',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Микролот'],
    rating: 4,
    acid: 'Низкая',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  {
    product: 'coffee',
    cookingMethod: 'Эспрессо',
    methodProcessing: 'Мытая',
    degreeFrying: 4,
    geography: 'Центр. Америка',
    typeCoffee: 'Смесь арабика/робуста',
    sale: false,
    special: ['Популярное', 'Новый урожай'],
    rating: 4,
    acid: 'Средняя',
    image: '../images/Discount Goods/01.png',
    title: 'Colombia Supremo',
    description: ['Свежеобжаренный кофе', '- описание товара, вкус, аромат'],
    price: '250',
  },
  //tea
  {
    product: 'tea',
    name: 'Черный чай',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/01.png',
    title: 'Наименование товара',
    description: ['Черный чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Зеленый чай',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/02.png',
    title: 'Наименование товара',
    description: ['Зеленый чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Молочный улунг',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/03.png',
    title: 'Наименование товара',
    description: ['Молочный улунг'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Травяной чай',
    sale: true,
    rating: 4,
    image: '../images/TeaCatalog/04.png',
    title: 'Наименование товара',
    description: ['Травяной чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Матча',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/05.png',
    title: 'Наименование товара',
    description: ['Матча'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Пуэр',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/06.png',
    title: 'Наименование товара',
    description: ['Пуэр'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Кофейные напитки',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/07.png',
    title: 'Наименование товара',
    description: ['Кофейные напитки'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Черный чай',
    sale: true,
    rating: 4,
    image: '../images/TeaCatalog/01.png',
    title: 'Наименование товара',
    description: ['Черный чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Зеленый чай',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/02.png',
    title: 'Наименование товара',
    description: ['Зеленый чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Молочный улунг',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/03.png',
    title: 'Наименование товара',
    description: ['Молочный улунг'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Травяной чай',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/04.png',
    title: 'Наименование товара',
    description: ['Травяной чай'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Матча',
    sale: true,
    rating: 4,
    image: '../images/TeaCatalog/05.png',
    title: 'Наименование товара',
    description: ['Матча'],
    price: '250 ₽',
  },
  //===================== 12 штук
  {
    product: 'tea',
    name: 'Пуэр',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/06.png',
    title: 'Наименование товара',
    description: ['Пуэр'],
    price: '250 ₽',
  },
  {
    product: 'tea',
    name: 'Кофейные напитки',
    sale: false,
    rating: 4,
    image: '../images/TeaCatalog/07.png',
    title: 'Наименование товара',
    description: ['Кофейные напитки'],
    price: '250 ₽',
  },
  //Wending Product
  {
    product: 'wending product',
    name: 'Гранулированный кофе',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный кофе'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный цикорий',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный цикорий'],
  },
  {
    product: 'wending product',
    name: 'Зерновой кофе',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Зерновой кофе'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный какао',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный какао'],
  },
  {
    product: 'wending product',
    name: 'Гранулированные кофейные напитки',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированные кофейные напитки'],
  },
  {
    product: 'wending product',
    name: 'Кофе порошкообразный',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Кофе порошкообразный'],
  },
  {
    product: 'wending product',
    name: 'Сухое молоко гранулированное',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Сухое молоко гранулированное'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный кофе',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный кофе'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный цикорий',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный цикорий'],
  },
  {
    product: 'wending product',
    name: 'Зерновой кофе',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Зерновой кофе'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный какао',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный какао'],
  },
  {
    product: 'wending product',
    name: 'Гранулированные кофейные напитки',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированные кофейные напитки'],
  },
  //=======================  12
  {
    product: 'wending product',
    name: 'Кофе порошкообразный',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Кофе порошкообразный'],
  },
  {
    product: 'wending product',
    name: 'Сухое молоко гранулированное',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Сухое молоко гранулированное'],
  },
  {
    product: 'wending product',
    name: 'Сухое молоко гранулированное',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Сухое молоко гранулированное'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный кофе',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный кофе'],
  },
  {
    product: 'wending product',
    name: 'Гранулированный цикорий',
    sale: false,
    rating: 4,
    image: '../images/Wending Products/01.png',
    title: 'Наименование товара',
    description: ['Гранулированный цикорий'],
  },
  //Healthy Diet
  {
    product: 'healthy diet',
    name: 'Цикорий и корень цикория',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Цикорий и корень цикория'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Ячменные напитки',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Ячменные напитки'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Напитки для здоровья',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Напитки для здоровья'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Протеиновые смеси',
    sale: true,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Протеиновые смеси'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Толокняные каши',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Толокняные каши'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Цикорий и корень цикория',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Цикорий и корень цикория'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Ячменные напитки',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Ячменные напитки'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Напитки для здоровья',
    sale: true,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Напитки для здоровья'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Протеиновые смеси',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Протеиновые смеси'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Толокняные каши',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Толокняные каши'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Цикорий и корень цикория',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Цикорий и корень цикория'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Напитки для здоровья',
    sale: true,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Напитки для здоровья'],
    price: '250 ₽',
  },
  //=========================== 12
  {
    product: 'healthy diet',
    name: 'Протеиновые смеси',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Протеиновые смеси'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Толокняные каши',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Толокняные каши'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Цикорий и корень цикория',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Цикорий и корень цикория'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Напитки для здоровья',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Напитки для здоровья'],
    price: '250 ₽',
  },
  {
    product: 'healthy diet',
    name: 'Протеиновые смеси',
    sale: false,
    rating: 4,
    image: '../images/HealthyDiet/01.png',
    title: 'Наименование товара',
    description: ['Протеиновые смеси'],
    price: '250 ₽',
  },
]

export const itemsBlogTraining = [
  {
    img: '../images/Blog/pic01.png',
    text: [
      'Разнообразный и богатый опыт новая модель организационной деятельности позволяет оценить значение позиций, занимаемых участниками в отношении поставленных задач. Значимость этих проблем настолько очевидна, что дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание модели развития.',

      'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия.Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития.',

      ' Товарищи! реализация намеченных плановых заданий обеспечивает широкому кругу(специалистов) участие в формировании соответствующий условий активизации.С другой стороны реализация намеченных плановых заданий требуют от нас анализа существенных финансовых и административных условий.'
    ]
  },
  {
    title: 'Название темы',
    img: '../images/Blog/pic02.png',
    text: [
      'Разнообразный и богатый опыт новая модель организационной деятельности позволяет оценить значение позиций, занимаемых участниками в отношении поставленных задач. Значимость этих проблем настолько очевидна, что дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание модели развития.',
      'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия.Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития.',
      ' Товарищи! реализация намеченных плановых заданий обеспечивает широкому кругу(специалистов) участие в формировании соответствующий условий активизации.С другой стороны реализация намеченных плановых заданий требуют от нас анализа существенных финансовых и административных условий.'
    ]
  },
  {
    title: 'Название темы',
    img: '../images/Blog/pic03.png',
    text: [
      'Разнообразный и богатый опыт новая модель организационной деятельности позволяет оценить значение позиций, занимаемых участниками в отношении поставленных задач. Значимость этих проблем настолько очевидна, что дальнейшее развитие различных форм деятельности в значительной степени обуславливает создание модели развития.',
      'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия.Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития.',
      ' Товарищи! реализация намеченных плановых заданий обеспечивает широкому кругу(специалистов) участие в формировании соответствующий условий активизации.С другой стороны реализация намеченных плановых заданий требуют от нас анализа существенных финансовых и административных условий.'
    ]
  },
]

export const itemsBlogNews = [
  {
    img: '../images/news/01.png',
    title: 'Танзанийский кофе. Откуда он взялся и почему мы его так любим?',
    text: ['Танзания – красивая африканская страна. Именно здесь расположены легендарные географические объекты – вулкан Килиманджаро и озеро Виктория.',

      'Но наш интерес вызван не столько природными красотами, сколько кофе...'],
    author: 'Автор статьи: Иван Иванов',
    link: 'Подробнее'
  },
  {
    img: '../images/news/01.png',
    title: 'Танзанийский кофе. Откуда он взялся и почему мы его так любим?',
    text: ['Танзания – красивая африканская страна. Именно здесь расположены легендарные географические объекты – вулкан Килиманджаро и озеро Виктория.',

      'Но наш интерес вызван не столько природными красотами, сколько кофе...'],
    author: 'Автор статьи: Иван Иванов',
    link: 'Подробнее'
  },
  {
    img: '../images/news/01.png',
    title: 'Танзанийский кофе. Откуда он взялся и почему мы его так любим?',
    text: ['Танзания – красивая африканская страна. Именно здесь расположены легендарные географические объекты – вулкан Килиманджаро и озеро Виктория.',

      'Но наш интерес вызван не столько природными красотами, сколько кофе...'],
    author: 'Автор статьи: Иван Иванов',
    link: 'Подробнее'
  },
]

export const itemsBlogNewsNav = [
  'Тег №1',
  'Тег №2',
  'Тег №3',
  'Тег №4',
  'Тег №5',
]

export const itemQuestion = [
  {
    title: 'Чем вы отличаетесь от конкурентов? Почему мне стоит выбрать вас?',
    text: 'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия. Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития',
  },
  {
    title: 'Чем вы отличаетесь от конкурентов? Почему мне стоит выбрать вас?',
    text: 'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия. Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития',
  },
  {
    title: 'Чем вы отличаетесь от конкурентов? Почему мне стоит выбрать вас?',
    text: 'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия. Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития',
  },
  {
    title: 'Чем вы отличаетесь от конкурентов? Почему мне стоит выбрать вас?',
    text: 'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия. Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития',
  },
  {
    title: 'Чем вы отличаетесь от конкурентов? Почему мне стоит выбрать вас?',
    text: 'Задача организации, в особенности же рамки и место обучения кадров способствует подготовки и реализации систем массового участия. Таким образом укрепление и развитие структуры способствует подготовки и реализации направлений прогрессивного развития',
  },
]

export const itemShopsContacts = [
  {
    city: 'Наши магазины г. Санкт-Петербург',
    address: ['Гороховая, 53', 'Московский, 53']
  },
  {
    city: 'Наши магазины Калининградская обл.',
    address: ['Советск, Гончарова 2а', 'Черняховск, Пионерская 1', 'Ульяны - Громовой 15', 'Советский проспект 6а',
      'Гурьевск, Каштановая 1г', 'Черняховского 15', 'Панина 2а', 'Ленинский 8Б', 'Аксакова 133', 'Липовая Аллея 2']
  }
]

export const deliveryOptions = [
  {
    text: 'СДЭК - до двери ',
    span: '390 ₽'
  },
  {
    text: 'Почта России ',
    span: '300 ₽'
  },
  {
    text: 'DPD - курьер, 3 дн ',
    span: '427 ₽'
  }
]
